version: '3.9'

services:
  mysql:
    container_name: lab_mysql
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_DATABASE=tef_resolver